#!/bin/bash
#SBATCH --comment=MAQ440-Prakt
#SBATCH --time=1-00:00
#SBATCH --mem-per-cpu=16000
#SBATCH --ntasks=1
#SBATCH --constraint=normalmem
#SBATCH --output=Wrfout_%j.txt
#SBATCH --error=Wrferr_%j.txt
#SBATCH --job-name=wrftest2
#SBATCH --mail-type=ALL
#SBATCH --mail-user=reinder.ronda@wur.nl
#SBATCH --constraint=avx512

ncl make2D.ncl
